### ISSUE TITLE
php7.0-fpm on ubuntu 首页文章 cover 不显示

### ISSUE THREAD

**Issue by thisforeda** [bayunjiang/yakumo#1]
在我所描述的情况下post/archive/page/index 这四个页面无法显示自定义的 cover.
我不会 php，但是稍微修改了一下 
`<?php if($this->fields->cover){$this->fields->cover();}`
成功显示cover，虽然与官方文档的做法不同。

https://github.com/ryanwschina/Yakumo/blob/master/archive.php#L33

**Comment by ryanwschina** [comment]
post/page cover在发表时用自定义字段插入。

**Comment by thisforeda** [comment]
发表文章时是添加了cover字段，就是这种情况下出现的这个问题。然后改成那样就又好了 🖍

**Comment by ryanwschina** [comment]
方便留下域名我看看么

**Comment by thisforeda** [comment]
本地调试的，没有放到网站。
