### ISSUE TITLE
icon 是方框无法显示

### ISSUE THREAD

**Issue by S8Cloud** [bayunjiang/yakumo#2]
icon 的图标无法正常显示，请问是什么原因
<img width="112" alt="2017-07-15 8 32 02" src="https://user-images.githubusercontent.com/27051990/28239330-cc18c4d0-699c-11e7-9a73-ee9037a51357.png">

**Comment by bayunjiang** [comment]
在 js/all.min.js 文件中搜索关键词"webfont.js"，将该相对路径修改成网站绝对路径即可。
